name: Code-Rollout
on:
  push:
    branches: [ main ]
    paths:
      - sources/**
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    environment: T1
    steps:
      - uses: actions/checkout@main
      
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      
      - name: Get Function App Publishing Profile
        uses: azure/powershell@v1
        id: webAppPublishingProfile
        with:
          inlineScript: |
            $PublishingProfile = Get-AzWebAppPublishingProfile -ResourceGroupName ITDL-WEU-WATCHDOG -Name itdl-weu-watchdog-app -Format "WebDeploy"
            echo "action_state=yellow" >> $GITHUB_ENV
          azPSVersion: 'latest'