name: Infrastructure-Rollout
on:
  push:
    branches: [ infrastructure ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a powershell
        run: |
          write-host $env:CLIENT_ID
        shell: pwsh
        env:
          CLIENT_ID: ${{secrets.SPN_CLIENT_ID}}