name: Infrastructure-Rollout
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            if $(az group exists --name ${{ secrets.ResourceGroupName }}) ; then
              echo "Azure resource group already exists, skipping creation..."
            else
              az group create --name ${{ secrets.ResourceGroupName }} --location ${{ secrets.ResourceGroupLocation }}
              echo "Azure resource group created"
            fi
      
      - uses: azure/arm-deploy@v1
        id: 'storageaccount'
        with:
          resourceGroupName: ${{ secrets.ResourceGroupName }}
          template: ./infrastructure/storage-account.bicep
          parameters: storageAccountName=${{ secrets.StorageAccountName }}

      - uses: azure/arm-deploy@v1
        id: 'appserviceplan'
        with:
          resourceGroupName: ${{ secrets.ResourceGroupName }}
          template: ./infrastructure/app-service-plan.bicep
          parameters: appServicePlanName=${{ secrets.appServicePlanName }}
      
      - uses: azure/arm-deploy@v1
        id: 'functionapp'
        with:
          resourceGroupName: ${{ secrets.ResourceGroupName }}
          template: ./infrastructure/function-app.bicep
          parameters: 
            functionAppName=${{ secrets.functionAppName }}
            appServicePlanResourceId=${{ steps.appserviceplan.outputs.appServicePlanResourceId }}
            storageAccountResourceId=${{ steps.storageaccount.outputs.storageAccountResourceId }}
